### ISSUE TITLE
When using GPS option in /procarro [plate] menu

### ISSUE THREAD

**Issue by Worryinglamb08** [Kuanaxd/kuana_garage#1]
Console throws this error
![2020-01-30_11h25_08](https://user-images.githubusercontent.com/58918753/73432247-5a075d00-4353-11ea-9ea5-2c372e126299.png)

**Comment by Kuanaxd** [comment]
I will update it its a simple fix

**Comment by Worryinglamb08** [comment]
Awesome will wait for update

**Comment by Kuanaxd** [comment]
Ok updated should work

**Comment by Worryinglamb08** [comment]
Testing now

**Comment by Worryinglamb08** [comment]
It works, thank you!

**Comment by Kuanaxd** [comment]
Y W :)
