### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by Timmyopp** [Kuanaxd/kuana_garage#2]
![Capture](https://user-images.githubusercontent.com/65283001/82129998-0456a380-97d0-11ea-83ae-2704a367a8ab.JPG)

How can i fix that?

**Comment by Timmyopp** [comment]
This happens when I use /garagem /procarro  and /givecarkeys

**Comment by ninny2104** [comment]
ESX.UI.Menu.Open(
			'default', GetCurrentResourceName(), 'spawn_vehiclereload',
			{
				title    = _U('garage'),
				align    = 'top-left',
				elements = elements,
			},
			
			function(data, menu)
			--	Citizen.Wait(50)
					for i=1, #veh, 1 do
						if veh then
							local vehiclePropsn  = ESX.Game.GetVehicleProperties(veh[i])
						
								-- do whatever threw the err
						if vehiclePropsn ~= nil and data.current.value.plate ~= nil then
							if vehiclePropsn.plate == data.current.value.plate then
								podespawn = false
								break
							else
								podespawn = true
							end
						else
							podespawn = true
						end
					tend
				--	return nil
			end

**Comment by Timmyopp** [comment]
Just noticed, Will try it out now, much thanks!
